name 'spring-petclinic-app-deploy'
maintainer 'Sales Eng'
maintainer_email 'saleseng@chef.io'
license 'all_rights'
description 'Deploys a Tomcat java application'
long_description 'A simple cookbook to deploy a java application'
source_url 'https://github.com/chef-cft/spring-petclinic-app-deploy'
issues_url 'https://github.com/chef-cft/spring-petclinic-app-deploy/issues'
version '0.2.6'

depends 'tomcat', '~> 2.3.1'
depends 'java'
